export const ROLES = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  LOAN_OFFICER: 'LOAN_OFFICER',
  AUDITOR: 'AUDITOR',
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

export const PERMISSIONS = {
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  VIEW_APPLICATIONS: 'VIEW_APPLICATIONS',
  MANAGE_APPLICATIONS: 'MANAGE_APPLICATIONS',
  VIEW_CUSTOMERS: 'VIEW_CUSTOMERS',
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',
  VIEW_AUDIT: 'VIEW_AUDIT',
  VIEW_ADMIN: 'VIEW_ADMIN',
  MANAGE_USERS: 'MANAGE_USERS',
  DISBURSE_LOANS: 'DISBURSE_LOANS',
} as const;

export const ROLE_PERMISSIONS: Record<Role, string[]> = {
  [ROLES.ADMIN]: Object.values(PERMISSIONS),
  [ROLES.MANAGER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_APPLICATIONS,
    PERMISSIONS.MANAGE_APPLICATIONS,
    PERMISSIONS.VIEW_CUSTOMERS,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.VIEW_AUDIT,
  ],
  [ROLES.LOAN_OFFICER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_APPLICATIONS,
    PERMISSIONS.MANAGE_APPLICATIONS,
    PERMISSIONS.VIEW_CUSTOMERS,
  ],
  [ROLES.AUDITOR]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_AUDIT,
  ],
};

export const ROUTE_PERMISSIONS: Record<string, string[]> = {
  '/': [PERMISSIONS.VIEW_DASHBOARD],
  '/applications': [PERMISSIONS.VIEW_APPLICATIONS],
  '/customers': [PERMISSIONS.VIEW_CUSTOMERS],
  '/analytics': [PERMISSIONS.VIEW_ANALYTICS],
  '/audit': [PERMISSIONS.VIEW_AUDIT],
  '/admin': [PERMISSIONS.VIEW_ADMIN],
};
